FROM python:2.7

MAINTAINER Jan Bernhard <janb@princeton.edu>

# Upgrade pip
RUN pip install --upgrade pip

# Install requirements
RUN mkdir /project && mkdir /project/setup
ADD ./project/setup/ /project/setup/
RUN pip install -r /project/setup/requirements.txt

# Install SUAVE
WORKDIR /project/setup/SUAVE/trunk
RUN python setup.py install

# Add project files
WORKDIR /project
RUN mkdir /main

# RUN pwd && ls
# COPY ./start.sh ./start.sh
# RUN chmod +x start.sh


RUN pwd
# ADD ./project/main /project/main
ADD ./project/main /main
RUN ls -la

# ENTRYPOINT ["entrypoint.sh"]
# CMD ["sleep 99999999;"]
